#!/usr/bin/env bash
#This script fixes an Nginx server so it can start listening on port 80
#sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
#sudo service nginx restart
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
