#!/usr/bin/env bash
#This script fixes an Nginx server so it can start listening on port 80
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
