#!/usr/bin/env bash
# This script displays numbers from 1 to 100, 
#displays Fizz when is a multiple of 3, Buzz for 5 and FizzBuzz for both

# Iterate 100 times
for i in {1..100}
do
	if (( $i % 3 == 0 && $i % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif (( $i % 3 == 0 ))
	then
		echo "Fizz"
	elif (( $i % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$i"
	fi
done
