#!/usr/bin/env bash
# This script sorts parsed Apache log file and groups visitors by
# IP and HTTP status code in list format: OCCURENCE_NUMBER IP HTTP_CODE
# from the greatest number of occurences to the lowest

awk '{ print $1 " " $9 }' apache-access.log | sort | uniq -c | sort -rn
