#!/usr/bin/env bash
# This script iterates 10 times and displays diff things at diff intervals

#initialize the counter
n=1

#iterate 10 times
while [ $n -le 10 ]
do
	if [ $n == 4 ]; then
		echo "bad luck"
	elif [ $n == 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( n++ ))
done
